import json, random, textwrap, os
random.seed(900)
entries = [
# Git and GitHub basics
{"domain":"Git and GitHub basics","label":"Version control","definition":"A system for tracking changes to files over time so you can compare versions, restore earlier work, and collaborate safely.","need":"track changes over time and recover older versions of files","explanation":"Version control records the history of changes, making collaboration safer and helping teams understand what changed, when, and why."},
{"domain":"Git and GitHub basics","label":"Distributed version control","definition":"A version control model where each developer has a full local copy of the repository history, not only a central server checkout.","need":"allow developers to work locally with a full project history before syncing changes","explanation":"Git is distributed, so contributors can commit, branch, compare, and inspect history locally before pushing to a remote."},
{"domain":"Git and GitHub basics","label":"Git","definition":"The distributed version control system used to track file changes, create commits, and manage branches on a local machine or server.","need":"record local commits, create branches, and manage source history from the command line or tools","explanation":"Git is the version control technology. GitHub is a platform that hosts Git repositories and adds collaboration features."},
{"domain":"Git and GitHub basics","label":"GitHub","definition":"A cloud-based developer platform for hosting Git repositories and collaborating with issues, pull requests, projects, Actions, Codespaces, and more.","need":"host a Git repository online and collaborate with others using pull requests and issues","explanation":"GitHub builds collaboration, project management, security, automation, and community features around Git repositories."},
{"domain":"Git and GitHub basics","label":"Repository","definition":"The project container that stores files, folders, commit history, branches, settings, and collaboration tools.","need":"store a project together with its files, history, branches, and settings","explanation":"A repository, often called a repo, is the main place where a project lives on GitHub."},
{"domain":"Git and GitHub basics","label":"Commit","definition":"A saved snapshot of staged changes in a Git repository, usually with a message describing the change.","need":"save a specific set of changes with a message in the project history","explanation":"Commits form the history of a repository and let you review, compare, and revert changes."},
{"domain":"Git and GitHub basics","label":"Commit SHA","definition":"A unique identifier generated for a commit, used to reference that exact point in repository history.","need":"refer to one exact commit without ambiguity","explanation":"A commit SHA uniquely identifies a commit, which is useful when reviewing history, comparing changes, or referencing fixes."},
{"domain":"Git and GitHub basics","label":"Branch","definition":"A movable line of development that lets you make changes independently from other work in the repository.","need":"work on a feature without directly changing the default branch","explanation":"Branches isolate work so changes can be reviewed and merged later."},
{"domain":"Git and GitHub basics","label":"Default branch","definition":"The primary branch of a repository, commonly named main, where stable or official work is often based.","need":"identify the primary branch that new pull requests and clones use by default","explanation":"The default branch is the base branch for many repository operations and is usually protected in important projects."},
{"domain":"Git and GitHub basics","label":"Merge","definition":"The process of combining changes from one branch into another branch.","need":"combine reviewed feature work back into the main line of development","explanation":"Merging integrates work from a source branch into a target branch after review or validation."},
{"domain":"Git and GitHub basics","label":"Clone","definition":"A local copy of a repository, including files and Git history, created from a remote repository.","need":"download a GitHub repository to a local computer for editing","explanation":"Cloning gives you a local working copy connected to the remote repository."},
{"domain":"Git and GitHub basics","label":"Fork","definition":"A personal copy of another repository under your account or organization, often used to propose changes to projects you do not control.","need":"make changes to an open-source project without direct write access to the original repository","explanation":"Forks support collaboration when contributors need their own copy before opening a pull request upstream."},
{"domain":"Git and GitHub basics","label":"Pull","definition":"A Git operation that gets changes from a remote repository and integrates them into the current local branch.","need":"bring remote changes into a local branch and update the working copy","explanation":"Pull is typically fetch plus integration, helping keep a local branch current with the remote."},
{"domain":"Git and GitHub basics","label":"Push","definition":"A Git operation that uploads local commits to a remote repository.","need":"send local commits from a computer to GitHub","explanation":"Pushing shares local commits with the remote repository so others and GitHub features can see them."},
{"domain":"Git and GitHub basics","label":"Fetch","definition":"A Git operation that downloads remote changes without automatically merging them into the current branch.","need":"check what changed on the remote before integrating those changes locally","explanation":"Fetch updates remote-tracking information while letting you decide when and how to merge or rebase."},
{"domain":"Git and GitHub basics","label":"Remote","definition":"A named connection to another copy of the repository, commonly the GitHub-hosted repository called origin.","need":"connect a local repository to its hosted copy on GitHub","explanation":"Remotes let Git know where to push commits and where to fetch or pull changes from."},
{"domain":"Git and GitHub basics","label":"Working tree","definition":"The checked-out files and folders you are currently editing in your local repository.","need":"refer to the files currently visible and editable on a developer's machine","explanation":"The working tree is where file edits happen before changes are staged and committed."},
{"domain":"Git and GitHub basics","label":"Staging area","definition":"The place where selected file changes are prepared before being saved in the next commit.","need":"choose exactly which edits should go into the next commit","explanation":"The staging area lets you craft focused commits instead of committing every local change at once."},
{"domain":"Git and GitHub basics","label":"Pull request","definition":"A GitHub collaboration feature for proposing changes, discussing them, running checks, and merging them into another branch.","need":"request review and approval before merging branch changes","explanation":"Pull requests are central to GitHub Flow because they combine discussion, review, automation, and merge control."},
{"domain":"Git and GitHub basics","label":"GitHub Flow","definition":"A lightweight workflow where you create a branch, commit changes, open a pull request, review and test, then merge and deploy.","need":"follow GitHub's common branch-based collaboration process","explanation":"GitHub Flow encourages small branches, pull requests, review, and frequent integration."},
{"domain":"Git and GitHub basics","label":"Markdown","definition":"A lightweight markup syntax used to format text such as headings, lists, links, code blocks, and checklists in GitHub.","need":"format an issue or pull request description with headings, checklists, and code blocks","explanation":"GitHub uses Markdown widely in README files, issues, pull requests, discussions, comments, and documentation."},
{"domain":"Git and GitHub basics","label":"Personal account","definition":"An individual GitHub identity used to create repositories, contribute to projects, and manage personal settings.","need":"represent one person on GitHub with their own profile, repositories, and settings","explanation":"A personal account is tied to an individual user and can be a member of organizations."},
{"domain":"Git and GitHub basics","label":"Organization","definition":"A shared GitHub account for teams or companies that manages repositories, members, teams, billing, and policies.","need":"manage many team repositories and permissions under a shared company account","explanation":"Organizations centralize collaboration and access management for groups of users."},
{"domain":"Git and GitHub basics","label":"Enterprise account","definition":"A top-level GitHub account type for centrally managing multiple organizations, policies, billing, identity, and security at scale.","need":"manage GitHub policies and billing across multiple organizations in a large company","explanation":"Enterprise accounts support organization-wide governance and centralized administration."},
{"domain":"Git and GitHub basics","label":"GitHub Desktop","definition":"A graphical desktop application for using Git and GitHub workflows without relying only on the command line.","need":"let a beginner commit, branch, push, and open pull requests using a GUI on their computer","explanation":"GitHub Desktop is useful for users who prefer a visual local Git client."},
{"domain":"Git and GitHub basics","label":"GitHub Mobile","definition":"A mobile app for managing notifications, reviewing issues and pull requests, and staying connected to GitHub work while away from a computer.","need":"review notifications and respond to GitHub activity from a phone","explanation":"GitHub Mobile is best for lightweight review and communication tasks on mobile devices."},
{"domain":"Git and GitHub basics","label":"Merge conflict","definition":"A situation where Git cannot automatically combine changes because different edits affect the same part of a file or history.","need":"describe why a merge cannot complete automatically and needs human resolution","explanation":"Merge conflicts require a person to choose the correct final content before completing the merge."},
{"domain":"Git and GitHub basics","label":"Commit message","definition":"The text attached to a commit that explains what changed and why.","need":"explain the purpose of a saved change in the repository history","explanation":"Clear commit messages make project history easier to understand and review."},
{"domain":"Git and GitHub basics","label":"Tag","definition":"A named pointer to a specific commit, often used to mark release versions.","need":"mark the commit that represents version 1.0.0 of a project","explanation":"Tags are commonly used to identify release points in repository history."},
{"domain":"Git and GitHub basics","label":"Release","definition":"A GitHub object that packages software at a tagged version and can include release notes and downloadable assets.","need":"publish versioned software with notes and attached build files","explanation":"Releases build on Git tags and provide a user-friendly way to distribute versions."},
{"domain":"Git and GitHub basics","label":"Rebase","definition":"A Git operation that reapplies commits onto another base commit to create a cleaner linear history.","need":"move feature branch commits onto the latest base branch history","explanation":"Rebase rewrites commit history, so it should be used carefully, especially on shared branches."},
{"domain":"Git and GitHub basics","label":"Repository owner","definition":"The user or organization that owns a repository and controls its settings, visibility, and access policies.","need":"identify who controls repository settings and permissions","explanation":"Ownership determines who can administer repository-level configuration and access."},
{"domain":"Git and GitHub basics","label":"Star","definition":"A way to bookmark or show interest in a repository, which can also help indicate popularity.","need":"save a repository for later and signal interest without receiving every notification","explanation":"Starring is different from watching; watching controls notifications."},
{"domain":"Git and GitHub basics","label":"Watch","definition":"A repository subscription setting that controls which notifications you receive for repository activity.","need":"receive notifications about activity in a repository","explanation":"Watching is used for notification management, while starring is mainly bookmarking or showing interest."},
{"domain":"Git and GitHub basics","label":"Issue reference","definition":"A shorthand such as #42 that links to an issue or pull request number in the same repository.","need":"link a discussion comment to a specific issue number quickly","explanation":"Issue references make GitHub conversations easier to navigate by linking related work."},

# Repositories
{"domain":"Repositories","label":"README file","definition":"A repository file, usually README.md, that introduces the project and explains how to use, install, or contribute to it.","need":"show visitors what a repository is for and how to get started","explanation":"README files are often the first documentation users see in a repository."},
{"domain":"Repositories","label":"LICENSE file","definition":"A file that explains the legal terms under which others may use, modify, and distribute a project.","need":"communicate how others are legally allowed to use an open-source project","explanation":"A license clarifies permissions and limitations for users and contributors."},
{"domain":"Repositories","label":"CONTRIBUTING file","definition":"A file that explains how people should contribute to a repository, including setup, process, and expectations.","need":"tell contributors how to submit issues, branches, pull requests, and style-compliant changes","explanation":"CONTRIBUTING.md helps standardize contribution behavior and reduce confusion."},
{"domain":"Repositories","label":"CODEOWNERS file","definition":"A file that defines people or teams responsible for specific paths so they can be requested for review automatically.","need":"automatically request reviews from the team responsible for files in a folder","explanation":"CODEOWNERS supports review routing and ownership of code areas."},
{"domain":"Repositories","label":"SECURITY file","definition":"A repository file that tells users how to report security vulnerabilities and what security policies apply.","need":"tell users how to privately report a vulnerability","explanation":"SECURITY.md helps set expectations for responsible vulnerability reporting."},
{"domain":"Repositories","label":".gitignore file","definition":"A file that lists patterns for files Git should ignore, such as build outputs, local settings, or dependency folders.","need":"avoid committing temporary files, logs, or local environment files","explanation":".gitignore prevents unwanted files from being tracked in repository history."},
{"domain":"Repositories","label":"Repository template","definition":"A repository configured so others can generate new repositories with the same starter files and structure.","need":"create many new projects with the same starter folders, README, and workflows","explanation":"Repository templates help standardize repeated project setup."},
{"domain":"Repositories","label":"Branch strategy","definition":"A planned approach for using branches, such as feature branches and a protected main branch, to organize development work.","need":"organize how features, fixes, and releases are developed without chaos","explanation":"A branch strategy helps teams coordinate work and reduce risk when merging changes."},
{"domain":"Repositories","label":"Create new file on GitHub","definition":"A web interface action that adds a file directly to a repository through GitHub without using a local clone.","need":"add a small README update directly from the browser","explanation":"GitHub lets users create or edit files in the browser for simple changes."},
{"domain":"Repositories","label":"Upload files on GitHub","definition":"A web interface feature for adding files to a repository by uploading them from your computer.","need":"add existing files from a computer into a repository through the browser","explanation":"Uploading files is useful for adding files without using command-line Git."},
{"domain":"Repositories","label":"Repository Insights","definition":"A GitHub area that shows repository activity, contributors, traffic, dependency graph, forks, and related visibility information.","need":"review project activity, contributors, traffic, and dependency information","explanation":"Insights help maintainers understand repository health and activity."},
{"domain":"Repositories","label":"Traffic graph","definition":"A repository insight that shows views and clone activity for a repository.","need":"see how many people viewed or cloned a repository recently","explanation":"Traffic insights help maintainers understand repository reach and usage."},
{"domain":"Repositories","label":"Dependency graph","definition":"A GitHub feature that detects dependencies and supports alerts and insights about packages used by a repository.","need":"see which packages a repository depends on and support vulnerability alerts","explanation":"The dependency graph powers several supply-chain security and visibility features."},
{"domain":"Repositories","label":"Repository topics","definition":"Short labels added to a repository to describe its subject, language, framework, or purpose for discovery.","need":"make a repository easier to find by subject such as react, finance, or portfolio","explanation":"Topics improve discoverability and help users understand what a repository is about."},
{"domain":"Repositories","label":"Repository description","definition":"A short text summary displayed near the repository name to explain what the project does.","need":"quickly explain a repository's purpose on its main page and search results","explanation":"A clear description helps visitors and collaborators understand the repository at a glance."},
{"domain":"Repositories","label":"Repository visibility","definition":"The setting that determines whether a repository is public, private, or internal where supported.","need":"control who can see a repository","explanation":"Visibility is a core repository setting for privacy and collaboration."},
{"domain":"Repositories","label":"Public repository","definition":"A repository visibility option that allows anyone on the internet to view the repository.","need":"share source code openly with everyone","explanation":"Public repositories are visible to anyone, though write access is still controlled."},
{"domain":"Repositories","label":"Private repository","definition":"A repository visibility option that limits visibility to explicitly granted users or teams.","need":"keep code visible only to approved collaborators","explanation":"Private repositories restrict who can see the repository contents."},
{"domain":"Repositories","label":"Internal repository","definition":"An enterprise visibility option that makes a repository visible to enterprise members but not the public internet.","need":"share a repository across an enterprise without making it public","explanation":"Internal visibility is useful for enterprise-wide collaboration while keeping work private externally."},
{"domain":"Repositories","label":"Repository archive","definition":"A read-only repository state used when a project is no longer actively maintained but should remain available.","need":"mark an inactive project as read-only while keeping it available for reference","explanation":"Archiving communicates that active maintenance has stopped and prevents normal write activity."},
{"domain":"Repositories","label":"Pinned repository","definition":"A repository selected to appear prominently on a GitHub profile or organization page.","need":"highlight important work on a profile page","explanation":"Pinned repositories help showcase selected projects."},
{"domain":"Repositories","label":"Feature preview","definition":"A GitHub setting area where users may try certain new or experimental GitHub features when available.","need":"enable an available experimental GitHub feature for testing","explanation":"Feature previews let users opt in to selected GitHub experiences before or during rollout."},
{"domain":"Repositories","label":"Repository settings","definition":"The administrative area where repository collaborators, branches, security, visibility, integrations, and other options are configured.","need":"change repository visibility, branch rules, or collaborator access","explanation":"Repository settings centralize configuration for a repository."},
{"domain":"Repositories","label":"Default branch rename","definition":"Changing the primary branch name, such as from master to main, while updating repository references.","need":"change the primary branch name used by a repository","explanation":"Renaming the default branch changes the primary branch and may require updating local clones or integrations."},
{"domain":"Repositories","label":"File history","definition":"The view of commits that changed a specific file in a repository.","need":"see how a particular file changed over time","explanation":"File history helps you investigate why and when changes were made to a file."},
{"domain":"Repositories","label":"Blame view","definition":"A view that shows which commit and author last changed each line of a file.","need":"identify when and by whom a specific line was last changed","explanation":"Blame is useful for investigating context, not for assigning personal fault."},

# Collaboration
{"domain":"Collaboration","label":"GitHub Issues","definition":"A GitHub feature for tracking bugs, tasks, feature requests, and other actionable work in a repository.","need":"track a bug report or feature request as actionable work","explanation":"Issues are designed for work tracking, triage, assignment, labels, and discussion around tasks."},
{"domain":"Collaboration","label":"GitHub Discussions","definition":"A GitHub feature for open-ended conversations, Q&A, ideas, and community discussions that are not necessarily trackable work items.","need":"host Q&A or idea conversations that are not bugs or tasks","explanation":"Discussions are better than issues for broad conversation and community support."},
{"domain":"Collaboration","label":"Pull request review","definition":"The process of reviewing proposed changes in a pull request using comments, approvals, or change requests.","need":"approve or request changes before code is merged","explanation":"Pull request reviews help teams improve quality and share knowledge before merging."},
{"domain":"Collaboration","label":"Draft pull request","definition":"A pull request state that signals work is not ready for final review or merge yet.","need":"share early work while clearly showing it is not ready to merge","explanation":"Draft pull requests are useful for early feedback without implying readiness."},
{"domain":"Collaboration","label":"Issue templates","definition":"Predefined forms or Markdown templates that guide users to provide useful information when opening issues.","need":"make bug reports include steps to reproduce, expected behavior, and screenshots","explanation":"Templates improve issue quality and reduce back-and-forth questions."},
{"domain":"Collaboration","label":"Pull request template","definition":"A predefined pull request description that prompts contributors to include relevant context, tests, or checklist items.","need":"make contributors include testing notes and related issue links in every pull request","explanation":"Pull request templates standardize review information."},
{"domain":"Collaboration","label":"Labels","definition":"Colored tags used to categorize and filter issues, pull requests, and discussions.","need":"categorize issues as bug, documentation, enhancement, or help wanted","explanation":"Labels help teams sort, filter, and prioritize work."},
{"domain":"Collaboration","label":"Assignees","definition":"Users assigned to an issue or pull request to indicate responsibility for the work.","need":"show who is responsible for handling a bug or reviewing a task","explanation":"Assignees clarify responsibility and ownership for a work item."},
{"domain":"Collaboration","label":"Milestones","definition":"Groups of issues and pull requests used to track progress toward a larger goal, version, or deadline.","need":"track all issues and pull requests required for a release version","explanation":"Milestones group related work and show completion progress."},
{"domain":"Collaboration","label":"Reviewers","definition":"People requested to review a pull request and provide feedback, approval, or requested changes.","need":"ask specific people to review a proposed code change","explanation":"Reviewers are part of the pull request workflow and help validate changes."},
{"domain":"Collaboration","label":"Mentions","definition":"Using @username or @team to notify a user or team in a GitHub conversation.","need":"bring a person's attention to a comment in an issue","explanation":"Mentions notify the referenced user or team, depending on permissions and notification settings."},
{"domain":"Collaboration","label":"Notifications","definition":"Alerts about GitHub activity that a user can receive and manage through inbox, email, mobile, or web settings.","need":"stay informed about pull requests, issues, mentions, and subscribed activity","explanation":"Notification settings help users manage workflow noise and attention."},
{"domain":"Collaboration","label":"Saved replies","definition":"Reusable comment text that can be inserted into GitHub conversations to answer common questions quickly.","need":"respond consistently to repeated contributor questions","explanation":"Saved replies save time and keep communication consistent."},
{"domain":"Collaboration","label":"Linked pull request","definition":"A pull request connected to an issue, often by using keywords like fixes or closes followed by an issue number.","need":"automatically close an issue when the related pull request is merged","explanation":"GitHub can link pull requests to issues and close issues when merging with supported keywords."},
{"domain":"Collaboration","label":"Task list","definition":"A Markdown checklist using bracket syntax to track small tasks in an issue, pull request, or comment.","need":"show a checklist of remaining work inside a pull request description","explanation":"Task lists make progress visible inside GitHub conversations."},
{"domain":"Collaboration","label":"GitHub Gist","definition":"A simple way to share code snippets, notes, or small files, either publicly or secretly.","need":"share a small code snippet without creating a full repository","explanation":"Gists are lightweight sharing tools for snippets and notes."},
{"domain":"Collaboration","label":"GitHub Wiki","definition":"A repository-associated space for longer-form documentation pages maintained alongside a project.","need":"create multi-page project documentation attached to a repository","explanation":"Wikis are suitable for longer reference documentation beyond a README."},
{"domain":"Collaboration","label":"GitHub Pages","definition":"A feature for publishing static websites from a GitHub repository.","need":"host a static project website directly from a repository","explanation":"GitHub Pages serves static site content such as documentation, portfolios, and project pages."},
{"domain":"Collaboration","label":"Conversation filters","definition":"Search and filter controls for narrowing issues and pull requests by labels, assignees, status, authors, review state, and other metadata.","need":"find only open bugs assigned to a specific person","explanation":"Filters help teams manage large numbers of issues and pull requests."},
{"domain":"Collaboration","label":"Issue forms","definition":"Structured issue templates that collect information using form fields instead of only free-form Markdown.","need":"make users fill required fields when reporting a bug","explanation":"Issue forms improve consistency and completeness in issue reports."},
{"domain":"Collaboration","label":"Pull request checks","definition":"Automated results, such as tests or builds, displayed on a pull request before merge.","need":"see whether automated tests passed before merging a pull request","explanation":"Checks provide quality signals and can be required by branch protection rules."},
{"domain":"Collaboration","label":"Merge queue","definition":"A GitHub feature that helps merge pull requests in an orderly way while validating that queued changes still pass required checks.","need":"avoid broken main branch when many approved pull requests are ready to merge","explanation":"Merge queues coordinate merging and validation for busy repositories."},
{"domain":"Collaboration","label":"Squash merge","definition":"A merge method that combines all commits from a pull request into one commit on the base branch.","need":"merge a pull request while keeping the base branch history compact","explanation":"Squash merging simplifies history by creating a single commit for the pull request."},
{"domain":"Collaboration","label":"Rebase and merge","definition":"A merge method that places pull request commits onto the base branch without a merge commit.","need":"keep a linear history while preserving individual pull request commits","explanation":"Rebase and merge avoids merge commits but changes the commit base."},
{"domain":"Collaboration","label":"Required reviewers","definition":"A rule or practice that requires specific reviews before a pull request can merge.","need":"make sure code cannot merge until approved by required reviewers","explanation":"Required review policies support quality control and shared ownership."},
{"domain":"Collaboration","label":"Conversation resolution","definition":"Marking a pull request review conversation as resolved after the feedback has been addressed.","need":"show that a review comment was handled before merging","explanation":"Resolving conversations helps reviewers track remaining discussion points."},

# Modern development practices
{"domain":"Modern development practices","label":"GitHub Actions","definition":"GitHub's automation platform for building, testing, deploying, and automating workflows from repository events.","need":"automate tests and deployments when code is pushed or a pull request is opened","explanation":"GitHub Actions is used for CI/CD and many other repository automation tasks."},
{"domain":"Modern development practices","label":"Workflow","definition":"A configurable automated process in GitHub Actions, defined in YAML, that runs jobs when triggered.","need":"define an automated process that runs tests on every pull request","explanation":"A workflow is the top-level automation definition in GitHub Actions."},
{"domain":"Modern development practices","label":".github/workflows directory","definition":"The repository folder where GitHub Actions workflow YAML files are stored.","need":"place YAML files so GitHub Actions can discover and run them","explanation":"Workflows are stored in the .github/workflows directory of a repository."},
{"domain":"Modern development practices","label":"Workflow trigger","definition":"An event, manual action, or schedule that starts a GitHub Actions workflow.","need":"run automation when a pull request opens or on a nightly schedule","explanation":"Triggers control when workflows run, such as push, pull_request, workflow_dispatch, or schedule."},
{"domain":"Modern development practices","label":"Job","definition":"A set of steps in a GitHub Actions workflow that runs on the same runner.","need":"group build steps that should run together on the same runner","explanation":"Workflows contain one or more jobs, and jobs contain steps."},
{"domain":"Modern development practices","label":"Step","definition":"An individual task in a GitHub Actions job, such as running a command or using an action.","need":"run npm install as one task inside an automation job","explanation":"Steps execute in order within a job unless configured otherwise."},
{"domain":"Modern development practices","label":"Action","definition":"A reusable unit of automation that can be used as a step in a GitHub Actions workflow.","need":"reuse an existing checkout task in a workflow","explanation":"Actions package repeatable automation logic for use in workflows."},
{"domain":"Modern development practices","label":"Runner","definition":"A machine that executes GitHub Actions jobs, either hosted by GitHub or self-hosted by the user or organization.","need":"provide the compute environment where workflow jobs execute","explanation":"Runners perform the actual work defined by GitHub Actions jobs."},
{"domain":"Modern development practices","label":"GitHub-hosted runner","definition":"A runner managed by GitHub that provides a ready-to-use environment for GitHub Actions jobs.","need":"run CI jobs without managing your own build machine","explanation":"GitHub-hosted runners reduce infrastructure management for common automation tasks."},
{"domain":"Modern development practices","label":"Self-hosted runner","definition":"A runner you manage yourself for GitHub Actions jobs, often used for custom hardware, private networks, or special environments.","need":"run workflows on company-controlled infrastructure with custom software","explanation":"Self-hosted runners give more control but require management and security care."},
{"domain":"Modern development practices","label":"CI/CD","definition":"Practices that automate building, testing, and delivering software changes frequently and reliably.","need":"automatically build, test, and deploy software changes","explanation":"CI/CD improves speed and reliability by validating and delivering changes through automation."},
{"domain":"Modern development practices","label":"Workflow secret","definition":"An encrypted value used by GitHub Actions workflows to store sensitive data such as tokens or passwords.","need":"use an API token in a workflow without hard-coding it in the repository","explanation":"Secrets protect sensitive values and should be referenced securely in workflows."},
{"domain":"Modern development practices","label":"Environment protection rule","definition":"A GitHub Actions deployment control that can require approvals or other conditions before deploying to an environment.","need":"require approval before a workflow deploys to production","explanation":"Environment protection rules add governance to deployments."},
{"domain":"Modern development practices","label":"Workflow status badge","definition":"A badge that displays the current status of a GitHub Actions workflow, often in a README.","need":"show whether the build is currently passing on the repository homepage","explanation":"Status badges communicate workflow health to visitors and maintainers."},
{"domain":"Modern development practices","label":"GitHub Copilot","definition":"An AI coding assistant that provides code suggestions, chat assistance, and related developer productivity features.","need":"get AI-powered code suggestions and help while developing","explanation":"Copilot assists developers by suggesting code and answering development questions, but users must still review outputs."},
{"domain":"Modern development practices","label":"Copilot for Individuals","definition":"A Copilot plan intended for individual developers using Copilot with their personal account.","need":"use Copilot personally without organization-wide management needs","explanation":"Copilot for Individuals is aimed at personal developer use rather than centralized company governance."},
{"domain":"Modern development practices","label":"Copilot Business","definition":"A Copilot plan for organizations that need policy controls and business-focused management for users.","need":"give an organization managed Copilot access with administrative controls","explanation":"Copilot Business supports organizational use and policy management beyond individual subscriptions."},
{"domain":"Modern development practices","label":"Copilot Enterprise","definition":"A Copilot plan for enterprises with advanced organization-wide capabilities and deeper enterprise integration.","need":"use Copilot at enterprise scale with advanced governance and integration needs","explanation":"Copilot Enterprise is designed for larger organizations needing enterprise-level features."},
{"domain":"Modern development practices","label":"Copilot Agent Mode","definition":"A Copilot capability where the assistant can plan and carry out multi-step coding tasks with developer oversight.","need":"have AI help perform a multi-step code change while the developer reviews the result","explanation":"Agent Mode is about AI assistance across tasks, not replacing human review or repository permissions."},
{"domain":"Modern development practices","label":"Copilot content exclusion","definition":"A policy or configuration used to stop Copilot from using specified repository content for certain Copilot features where supported.","need":"prevent selected repository content from being used by Copilot features","explanation":"Content exclusion helps organizations control which code Copilot can reference for supported experiences."},
{"domain":"Modern development practices","label":"Multi-model Copilot support","definition":"The ability for Copilot experiences to support more than one AI model option where available.","need":"choose among supported AI model options for Copilot tasks","explanation":"The GH-900 outline includes awareness that Copilot can involve multi-model support."},
{"domain":"Modern development practices","label":"GitHub Codespaces","definition":"A cloud-hosted development environment connected to a repository, with editor, terminal, compute, and configurable dev environment.","need":"open a full cloud development environment without configuring a local machine","explanation":"Codespaces provides cloud compute and a complete development environment for a repository."},
{"domain":"Modern development practices","label":"Dev container","definition":"A container-based configuration that defines the tools, settings, extensions, and environment for a Codespace or compatible development setup.","need":"standardize the development environment so all contributors use the same tools","explanation":"Dev containers help make development environments reproducible and consistent."},
{"domain":"Modern development practices","label":"devcontainer.json","definition":"The configuration file that defines a development container's settings, extensions, ports, and setup commands.","need":"configure tools and extensions for a Codespaces environment","explanation":"devcontainer.json is central to customizing dev container behavior."},
{"domain":"Modern development practices","label":"Port forwarding in Codespaces","definition":"A feature that lets services running inside a codespace be accessed through forwarded ports.","need":"preview a web app running inside a codespace","explanation":"Port forwarding exposes local services from the cloud environment for testing and preview."},
{"domain":"Modern development practices","label":"github.dev editor","definition":"A lightweight browser-based editor for GitHub repositories that is useful for quick edits and code browsing without a full cloud compute environment.","need":"make a quick repository edit in a browser without starting a full development environment","explanation":"github.dev is lighter than Codespaces and does not provide the same full compute environment."},
{"domain":"Modern development practices","label":"Codespaces prebuild","definition":"A prepared codespace environment that reduces startup time by building common setup work in advance.","need":"make cloud development environments open faster for a repository","explanation":"Prebuilds improve startup speed by preparing dependencies and setup ahead of time."},
{"domain":"Modern development practices","label":"GitHub Marketplace action","definition":"A reusable automation published in GitHub Marketplace that can be used in workflows.","need":"find a community action to add to a CI workflow","explanation":"Marketplace helps users discover apps and actions that extend GitHub workflows."},
{"domain":"Modern development practices","label":"Manual workflow dispatch","definition":"A GitHub Actions trigger that allows a workflow to be started manually by a user.","need":"let a maintainer run a deployment workflow on demand","explanation":"workflow_dispatch enables manually triggered workflows."},
{"domain":"Modern development practices","label":"Scheduled workflow","definition":"A GitHub Actions workflow configured to run automatically at specified times using a schedule.","need":"run dependency checks every night without a code change","explanation":"Scheduled workflows support recurring automation."},

# Projects
{"domain":"Projects","label":"GitHub Projects","definition":"A flexible planning and tracking tool for organizing issues, pull requests, draft items, fields, views, and workflows.","need":"track feature work across issues and pull requests in a flexible planning board","explanation":"GitHub Projects helps teams plan, visualize, and manage work within GitHub."},
{"domain":"Projects","label":"Project table view","definition":"A GitHub Projects layout that displays project items in rows and fields in columns, similar to a spreadsheet.","need":"manage work items in a spreadsheet-like layout","explanation":"Table view is useful for structured tracking and sorting by fields."},
{"domain":"Projects","label":"Project board view","definition":"A GitHub Projects layout that displays items as cards grouped into columns, often by status.","need":"visualize work moving from Todo to In progress to Done","explanation":"Board view supports Kanban-style planning."},
{"domain":"Projects","label":"Project roadmap view","definition":"A GitHub Projects layout for viewing work over time using date-based fields.","need":"see planned work across a timeline","explanation":"Roadmap views help teams understand schedule and timing."},
{"domain":"Projects","label":"Project fields","definition":"Custom data columns in GitHub Projects, such as status, priority, iteration, date, number, or text fields.","need":"track priority and status for each project item","explanation":"Fields let teams capture metadata that supports filtering, grouping, sorting, and reporting."},
{"domain":"Projects","label":"Project status field","definition":"A field commonly used to represent the workflow state of an item, such as Todo, In progress, or Done.","need":"show whether each task is not started, active, or complete","explanation":"Status fields are common for visualizing progress in boards and tables."},
{"domain":"Projects","label":"Project workflows","definition":"Automation rules in GitHub Projects that update items or fields when defined events occur.","need":"automatically move an item to Done when its linked pull request is merged","explanation":"Project workflows reduce manual tracking work by automating project updates."},
{"domain":"Projects","label":"Project insights","definition":"Charts and views that help analyze project progress, status, and productivity trends.","need":"understand project progress and bottlenecks using charts","explanation":"Insights help teams make decisions from project data."},
{"domain":"Projects","label":"Project item","definition":"An issue, pull request, draft issue, or other tracked unit of work inside a GitHub Project.","need":"represent a single task inside a project plan","explanation":"Project items are the trackable units that appear in project views."},
{"domain":"Projects","label":"Draft issue","definition":"A project planning item that is not yet a full repository issue.","need":"capture an early idea in a project before turning it into an issue","explanation":"Draft issues are useful for lightweight planning before formalizing work."},
{"domain":"Projects","label":"Iteration field","definition":"A GitHub Projects field used to group work into repeating time boxes such as sprints.","need":"plan work into two-week sprints","explanation":"Iteration fields support sprint-like planning cycles."},
{"domain":"Projects","label":"Project filtering","definition":"Using filters to narrow project items by field values, assignees, labels, repositories, or other criteria.","need":"show only high-priority items assigned to a specific person","explanation":"Filtering makes large projects easier to focus and manage."},
{"domain":"Projects","label":"Project sorting","definition":"Ordering project items based on field values such as priority, due date, or status.","need":"show tasks from highest priority to lowest priority","explanation":"Sorting helps teams view work in the most useful order."},
{"domain":"Projects","label":"Project grouping","definition":"Organizing project items into sections based on a field such as status, assignee, or iteration.","need":"group tasks by assignee or sprint","explanation":"Grouping helps teams see work distribution and workflow state."},
{"domain":"Projects","label":"Labels in planning","definition":"Repository labels used in issues and pull requests to categorize project work for tracking and filtering.","need":"tag work as bug, docs, enhancement, or blocked for project planning","explanation":"Labels support triage, filtering, and planning across issues and pull requests."},
{"domain":"Projects","label":"Milestones in planning","definition":"GitHub milestones used to group issues and pull requests toward a release, deadline, or goal.","need":"track all tasks that belong to a release goal","explanation":"Milestones are useful for progress toward a defined deliverable."},
{"domain":"Projects","label":"Assignees in planning","definition":"Assigned users who are responsible for project work items such as issues or pull requests.","need":"make responsibility visible in a project tracker","explanation":"Assignees help clarify ownership and accountability."},
{"domain":"Projects","label":"Saved replies in planning","definition":"Reusable responses that help maintainers communicate quickly and consistently while managing project work.","need":"quickly answer repeated questions during issue triage","explanation":"Saved replies streamline communication during project and issue management."},
{"domain":"Projects","label":"Project view","definition":"A saved layout and filter configuration in GitHub Projects for looking at the same work in different ways.","need":"switch between a board for status and a table for priorities","explanation":"Views allow the same project data to be visualized for different audiences or needs."},
{"domain":"Projects","label":"Project template","definition":"A reusable project setup that helps teams start with predefined views, fields, or workflows.","need":"start similar projects with the same tracking setup","explanation":"Templates reduce setup effort and encourage consistent project management."},

# Security/admin
{"domain":"Security and administration","label":"Two-factor authentication","definition":"An account security method that requires a second factor, such as an app code or security key, in addition to a password.","need":"protect an account even if the password is stolen","explanation":"2FA reduces the risk of account takeover because a password alone is not enough."},
{"domain":"Security and administration","label":"Passkey","definition":"A passwordless sign-in credential based on public-key cryptography that can be used for secure authentication.","need":"sign in securely without relying on a traditional password","explanation":"Passkeys provide phishing-resistant authentication when supported by the account and device."},
{"domain":"Security and administration","label":"Repository role: Read","definition":"A permission level that allows viewing and cloning repository content but not pushing changes.","need":"let someone view code without making changes","explanation":"Read access is the least privileged repository role for viewing repository content."},
{"domain":"Security and administration","label":"Repository role: Triage","definition":"A permission level that can manage issues and pull requests without write access to code.","need":"let a support person label and manage issues without changing files","explanation":"Triage supports issue and pull request management while limiting code modification rights."},
{"domain":"Security and administration","label":"Repository role: Write","definition":"A permission level that allows pushing changes to the repository and managing normal development work.","need":"let a developer push commits and contribute code directly","explanation":"Write access is appropriate for contributors trusted to change repository content."},
{"domain":"Security and administration","label":"Repository role: Maintain","definition":"A permission level for managing repository operations without full access to sensitive or destructive admin settings.","need":"let a lead manage repository operations without giving full admin control","explanation":"Maintain provides elevated repository management while preserving separation from full administration."},
{"domain":"Security and administration","label":"Repository role: Admin","definition":"The highest repository-level role, allowing full control over repository settings, access, and potentially destructive actions.","need":"give someone full control over repository settings and access","explanation":"Admin access should be limited because it grants broad control."},
{"domain":"Security and administration","label":"Organization owner","definition":"An organization role with broad administrative control over organization settings, repositories, teams, billing, and policies.","need":"administer an entire GitHub organization","explanation":"Organization owners have powerful permissions and should be assigned carefully."},
{"domain":"Security and administration","label":"Organization member","definition":"A normal user role within a GitHub organization whose access depends on team and repository permissions.","need":"add someone to an organization without giving full owner control","explanation":"Members can collaborate according to the permissions granted to them."},
{"domain":"Security and administration","label":"Team","definition":"A group of organization members used to manage repository access and mention groups of people.","need":"grant the same repository access to several developers at once","explanation":"Teams simplify permission management and communication in organizations."},
{"domain":"Security and administration","label":"Least privilege","definition":"The security practice of giving users only the minimum access they need to do their work.","need":"choose a safe permission level for a user who only needs to triage issues","explanation":"Least privilege reduces risk if an account is misused or compromised."},
{"domain":"Security and administration","label":"Branch protection rule","definition":"A repository rule that enforces requirements before changes can be pushed or merged into matching branches.","need":"require reviews and passing tests before merging into main","explanation":"Branch protection helps protect important branches from unreviewed or failing changes."},
{"domain":"Security and administration","label":"Required status checks","definition":"Branch protection requirements that selected checks must pass before a pull request can merge.","need":"block merging unless automated tests pass","explanation":"Required status checks enforce automated validation before integration."},
{"domain":"Security and administration","label":"Required pull request reviews","definition":"A branch protection setting that requires one or more reviews before merging changes.","need":"ensure another person approves code before it enters main","explanation":"Required reviews support code quality and reduce risk."},
{"domain":"Security and administration","label":"Secret scanning","definition":"A GitHub security feature that detects secrets such as tokens or keys committed to repositories.","need":"detect accidentally committed credentials","explanation":"Secret scanning helps identify exposed credentials so they can be revoked and removed."},
{"domain":"Security and administration","label":"Code scanning","definition":"A GitHub security feature that analyzes code for vulnerabilities and coding errors, often using CodeQL or third-party tools.","need":"find potential security vulnerabilities in source code","explanation":"Code scanning helps discover insecure code patterns and bugs."},
{"domain":"Security and administration","label":"Dependabot alerts","definition":"Notifications about vulnerable dependencies detected in a repository's dependency graph.","need":"know when a package used by the project has a known vulnerability","explanation":"Dependabot alerts help teams identify vulnerable dependencies."},
{"domain":"Security and administration","label":"Dependabot security updates","definition":"Automated pull requests that update vulnerable dependencies to safer versions when possible.","need":"automatically open pull requests to fix vulnerable dependencies","explanation":"Security updates help remediate known dependency vulnerabilities."},
{"domain":"Security and administration","label":"Dependabot version updates","definition":"Automated pull requests that keep dependencies updated even when no vulnerability is involved.","need":"regularly update dependencies to newer versions for maintenance","explanation":"Version updates are for dependency freshness, while security updates target vulnerabilities."},
{"domain":"Security and administration","label":"Security advisory","definition":"A GitHub feature for privately discussing, fixing, and publishing information about a repository vulnerability.","need":"coordinate a vulnerability fix before publicly disclosing it","explanation":"Security advisories support responsible vulnerability handling."},
{"domain":"Security and administration","label":"Security policy","definition":"A repository policy, commonly in SECURITY.md, that explains supported versions and how to report vulnerabilities.","need":"tell users what versions are supported and how to report security issues","explanation":"A security policy helps users report vulnerabilities through the right process."},
{"domain":"Security and administration","label":"Enterprise Managed Users","definition":"A GitHub Enterprise feature where user accounts are provisioned and controlled by the enterprise identity provider.","need":"centrally manage GitHub identities through the company's identity system","explanation":"EMUs help enterprises control user lifecycle, identity, and access at scale."},
{"domain":"Security and administration","label":"Copilot policy management","definition":"Administrative controls for enabling, disabling, or configuring Copilot use across an organization or enterprise.","need":"control which users or repositories can use Copilot in an organization","explanation":"Copilot policy management supports governance for AI coding assistance."},
{"domain":"Security and administration","label":"Audit log","definition":"A record of important actions in an organization or enterprise used for monitoring, investigation, and compliance.","need":"investigate who changed a repository setting","explanation":"Audit logs help administrators review security-relevant activity."},
{"domain":"Security and administration","label":"Security manager role","definition":"An organization role that can manage security alerts and settings without necessarily being an organization owner.","need":"delegate security alert management to a security team","explanation":"Security manager access helps separate security duties from full organization ownership."},
{"domain":"Security and administration","label":"Fine-grained personal access token","definition":"A token that can be limited to specific repositories and permissions for GitHub API or Git operations.","need":"grant an integration limited access to only one repository","explanation":"Fine-grained tokens support least privilege better than broad credentials."},
{"domain":"Security and administration","label":"Organization settings","definition":"The administrative area for configuring organization members, teams, repository defaults, security, billing, and policies.","need":"change organization-wide member or security policies","explanation":"Organization settings centralize management for the organization."},
{"domain":"Security and administration","label":"Repository rulesets","definition":"Rules that define protections and restrictions for branches or tags across repositories or organizations.","need":"apply consistent branch rules across multiple repositories","explanation":"Rulesets help enforce policies consistently at scale."},
{"domain":"Security and administration","label":"Vulnerability reporting","definition":"A GitHub feature that lets users privately report vulnerabilities to repository maintainers when enabled.","need":"allow responsible disclosure without opening a public issue","explanation":"Private vulnerability reporting helps protect users while maintainers investigate and fix issues."},
{"domain":"Security and administration","label":"Collaborator","definition":"A user granted access to a repository, especially in a personal repository or outside normal organization team access.","need":"give one outside contributor access to a private repository","explanation":"Collaborators can be granted specific repository permissions."},

# Community
{"domain":"GitHub community","label":"Open source","definition":"A development model where source code is made available for others to inspect, use, modify, and contribute under a license.","need":"share code publicly so others can use and contribute under clear terms","explanation":"Open source depends on accessible code, licensing, collaboration, and community norms."},
{"domain":"GitHub community","label":"GitHub Sponsors","definition":"A GitHub program that lets people financially support open-source contributors and maintainers.","need":"financially support a maintainer of an open-source project","explanation":"Sponsors helps sustain open-source work through funding."},
{"domain":"GitHub community","label":"GitHub Marketplace","definition":"A place to discover GitHub Apps, OAuth apps, and Actions that extend GitHub workflows.","need":"find an app or action that adds functionality to GitHub","explanation":"Marketplace helps users discover integrations and automation for GitHub."},
{"domain":"GitHub community","label":"Following users","definition":"Subscribing to a user's public activity so you can stay informed about their work on GitHub.","need":"stay updated on another developer's public GitHub activity","explanation":"Following helps users discover activity and projects from people they care about."},
{"domain":"GitHub community","label":"Following organizations","definition":"Subscribing to an organization's public activity or updates to stay informed about its GitHub work.","need":"keep track of public activity from a company or open-source group","explanation":"Following organizations can help you stay informed about projects and announcements."},
{"domain":"GitHub community","label":"Discoverable repository","definition":"A repository made easier to find through public visibility, clear metadata, topics, README, and community files.","need":"make an open-source repository easier for others to find and understand","explanation":"Discoverability improves collaboration by helping contributors understand and locate projects."},
{"domain":"GitHub community","label":"Repository fork for collaboration","definition":"Using a fork as a personal workspace for changes before proposing them back to the original project.","need":"contribute to a public project without direct write access","explanation":"Forks are common in open-source collaboration because they let anyone propose changes safely."},
{"domain":"GitHub community","label":"Repository template for reuse","definition":"Using a template repository to create a new project with a starter structure but without copying the full fork relationship.","need":"start a new independent project from a standard structure","explanation":"Templates are better than forks when the goal is reuse rather than contributing back upstream."},
{"domain":"GitHub community","label":"InnerSource","definition":"Applying open-source practices such as transparent collaboration, shared ownership, and pull requests inside an organization.","need":"use open-source collaboration practices within a private company","explanation":"InnerSource brings open collaboration patterns to internal repositories and teams."},
{"domain":"GitHub community","label":"Community profile","definition":"A repository health view showing recommended community files such as README, LICENSE, CONTRIBUTING, and CODE_OF_CONDUCT.","need":"check whether a project has key community health files","explanation":"A complete community profile helps projects welcome and guide contributors."},
{"domain":"GitHub community","label":"Code of conduct","definition":"A community file that sets behavior expectations and reporting processes for project participants.","need":"define expected behavior for contributors in an open-source community","explanation":"A code of conduct supports a respectful and safe community environment."},
{"domain":"GitHub community","label":"Good first issue","definition":"A label commonly used to identify beginner-friendly issues for new contributors.","need":"help new contributors find approachable tasks","explanation":"Good first issue signals that a task is suitable for newcomers."},
{"domain":"GitHub community","label":"Help wanted label","definition":"A label used to show that maintainers are inviting community contributions on an issue.","need":"signal that outside contributors are welcome to work on a task","explanation":"Help wanted encourages community participation."},
{"domain":"GitHub community","label":"Contributor guidelines","definition":"Documentation that explains how to contribute to a project, often placed in CONTRIBUTING.md.","need":"teach new contributors the project's contribution process","explanation":"Contributor guidelines reduce confusion and improve contribution quality."},
{"domain":"GitHub community","label":"Social coding","definition":"Collaborative software development practices supported by public profiles, repositories, followers, stars, forks, issues, and pull requests.","need":"describe GitHub's community-centered collaboration model","explanation":"GitHub combines code hosting with social and collaborative features."},
{"domain":"GitHub community","label":"Public profile README","definition":"A special README shown on a user's GitHub profile when placed in a repository matching the username.","need":"customize a GitHub profile with personal project information","explanation":"Profile READMEs let users present themselves and their work on GitHub."},
{"domain":"GitHub community","label":"GitHub Community Discussions","definition":"A public support and discussion space where GitHub users can ask questions and share knowledge.","need":"ask community questions about GitHub usage","explanation":"Community Discussions are for peer support and knowledge sharing."},
{"domain":"GitHub community","label":"Maintainer","definition":"A person responsible for reviewing contributions, managing issues, making releases, and guiding a project.","need":"identify who guides an open-source repository and reviews contributions","explanation":"Maintainers help keep projects healthy and organized."},
{"domain":"GitHub community","label":"Contributor","definition":"A person who provides changes, documentation, bug reports, reviews, or other help to a project.","need":"describe someone who opens a pull request or improves documentation","explanation":"Contributions can include more than code, such as documentation, triage, and testing."},
{"domain":"GitHub community","label":"Issue triage","definition":"The process of reviewing, labeling, prioritizing, assigning, or closing issues.","need":"organize incoming bug reports and feature requests","explanation":"Triage helps maintainers keep project work understandable and actionable."},
{"domain":"GitHub community","label":"Release notes","definition":"Documentation that explains changes, fixes, and updates included in a software release.","need":"tell users what changed in a new version","explanation":"Release notes help users and contributors understand the impact of a release."},
{"domain":"GitHub community","label":"Open-source license selection","definition":"Choosing a license to define how others may use, modify, distribute, and contribute to code.","need":"make permissions clear before inviting public reuse of a repository","explanation":"Without a license, legal reuse rights may be unclear."},
{"domain":"GitHub community","label":"Topics for discovery","definition":"Repository metadata tags that help people find projects by technology, subject, or purpose.","need":"make a project appear in searches for a framework or subject area","explanation":"Topics are important for discoverability in the GitHub community."},
{"domain":"GitHub community","label":"Starred repositories list","definition":"A user's saved list of repositories they starred for later reference or interest.","need":"find repositories previously bookmarked with stars","explanation":"Stars help users bookmark and signal interest in repositories."},
{"domain":"GitHub community","label":"Open-source funding visibility","definition":"Repository funding links that show how users can financially support a project or maintainer.","need":"show sponsorship or donation options on a repository","explanation":"Funding visibility helps users support open-source maintainers."},
]

# Generate two questions per entry using same-domain distractors.
by_domain = {}
for e in entries:
    by_domain.setdefault(e['domain'], []).append(e)

def distractors(entry, k=3):
    pool = [x['label'] for x in by_domain[entry['domain']] if x['label'] != entry['label']]
    if len(pool) < k:
        pool = [x['label'] for x in entries if x['label'] != entry['label']]
    return random.sample(pool, k)

questions = []
for e in entries:
    opts = distractors(e)
    questions.append({
        "domain": e["domain"],
        "question": f"Which GitHub/Git term matches this description: {e['definition']}",
        "options": [e['label']] + opts,
        "answer": e['label'],
        "explanation": e['explanation']
    })
    opts2 = distractors(e)
    questions.append({
        "domain": e["domain"],
        "question": f"A team needs to {e['need']}. Which option is the best fit?",
        "options": [e['label']] + opts2,
        "answer": e['label'],
        "explanation": e['explanation']
    })

# Add a few mixed scenario questions with explicitly crafted options to increase exam-style variety.
extra = [
{"domain":"Git and GitHub basics","question":"Which sequence best represents GitHub Flow?","options":["Create a branch, commit changes, open a pull request, review/test, merge","Edit main directly, deploy, then ask for review","Fork, delete history, rename the repository, publish a release","Create an issue, archive the repository, then enable Pages"],"answer":"Create a branch, commit changes, open a pull request, review/test, merge","explanation":"GitHub Flow is based on branch-based work, pull requests, review, validation, and merging."},
{"domain":"Git and GitHub basics","question":"What is the main difference between Git and GitHub?","options":["Git is version control; GitHub is a hosting and collaboration platform built around Git","GitHub is a command-line tool; Git is a social network","Git stores issues; GitHub only stores local commits","They are the same product with different names"],"answer":"Git is version control; GitHub is a hosting and collaboration platform built around Git","explanation":"Git tracks changes and history. GitHub hosts repositories and adds collaboration, automation, security, and community features."},
{"domain":"Repositories","question":"Which repository file is most directly related to legal reuse rights?","options":["LICENSE file","README file","CODEOWNERS file",".gitignore file"],"answer":"LICENSE file","explanation":"A LICENSE file defines permissions and limitations for using, modifying, and distributing the project."},
{"domain":"Repositories","question":"Which file should explain how to report vulnerabilities responsibly?","options":["SECURITY file","README file","CONTRIBUTING file","CODEOWNERS file"],"answer":"SECURITY file","explanation":"SECURITY.md normally explains supported versions and vulnerability reporting instructions."},
{"domain":"Collaboration","question":"A maintainer wants broad community Q&A without treating every post as a task. What should they use?","options":["GitHub Discussions","GitHub Issues","Required status checks","Blame view"],"answer":"GitHub Discussions","explanation":"Discussions are designed for open-ended conversation, Q&A, announcements, and ideas."},
{"domain":"Collaboration","question":"A pull request should automatically close issue #18 after it merges. Which description format is best?","options":["Use a closing keyword such as Fixes #18","Star the issue","Add #18 to .gitignore","Rename the branch to issue-18-only"],"answer":"Use a closing keyword such as Fixes #18","explanation":"Supported keywords such as fixes, closes, or resolves can link a pull request and close the issue when merged."},
{"domain":"Modern development practices","question":"Where are GitHub Actions workflow files normally stored?","options":[".github/workflows",".github/issues","docs/actions","workflow/main"],"answer":".github/workflows","explanation":"GitHub Actions discovers workflow YAML files in the .github/workflows directory."},
{"domain":"Modern development practices","question":"Which option best distinguishes github.dev from Codespaces?","options":["github.dev is a lightweight web editor; Codespaces provides a full cloud development environment with compute","github.dev requires a self-hosted runner; Codespaces only edits Markdown","github.dev is for billing; Codespaces is for licenses","There is no difference"],"answer":"github.dev is a lightweight web editor; Codespaces provides a full cloud development environment with compute","explanation":"github.dev is useful for quick browser edits, while Codespaces provides a fuller cloud environment with terminal and compute."},
{"domain":"Projects","question":"Which GitHub Projects view is best for a Kanban-style workflow?","options":["Project board view","Project roadmap view","Blame view","Dependency graph"],"answer":"Project board view","explanation":"Board view shows cards in columns such as Todo, In progress, and Done."},
{"domain":"Projects","question":"Which GitHub Projects feature can automatically move an item when a pull request is merged?","options":["Project workflows","Repository topics","Gists","Passkeys"],"answer":"Project workflows","explanation":"Project workflows automate project field and item changes based on events."},
{"domain":"Security and administration","question":"Which control is best for preventing direct unreviewed changes to main?","options":["Branch protection rule","Starred repositories list","GitHub Gist","Public profile README"],"answer":"Branch protection rule","explanation":"Branch protection can require pull requests, reviews, and passing checks before changes enter important branches."},
{"domain":"Security and administration","question":"Which option should be used to detect accidentally committed tokens?","options":["Secret scanning","Project roadmap view","GitHub Pages","Saved replies"],"answer":"Secret scanning","explanation":"Secret scanning is designed to detect exposed credentials such as tokens and keys."},
{"domain":"Security and administration","question":"Which Dependabot feature opens pull requests for vulnerable dependencies?","options":["Dependabot security updates","Dependabot version updates","Project insights","Repository topics"],"answer":"Dependabot security updates","explanation":"Dependabot security updates create pull requests to update dependencies with known vulnerabilities."},
{"domain":"GitHub community","question":"A company wants to use open-source style collaboration internally. What is this called?","options":["InnerSource","GitHub Sponsors","Public repository","Starred repositories list"],"answer":"InnerSource","explanation":"InnerSource applies open-source principles inside an organization."},
{"domain":"GitHub community","question":"Which feature helps users financially support open-source maintainers?","options":["GitHub Sponsors","GitHub Pages","Branch protection","Issue forms"],"answer":"GitHub Sponsors","explanation":"GitHub Sponsors provides a way to fund open-source contributors and maintainers."},
]
questions.extend(extra)

# Keep options in authored order; app will shuffle choices on display.
# Give stable IDs.
for i, q in enumerate(questions, 1):
    q['id'] = f"GH900-{i:03d}"

out_dir = "/mnt/data/gh900-quiz"
os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, "questions.js"), "w", encoding="utf-8") as f:
    f.write("// Original GH-900 practice questions aligned to the Microsoft Learn study guide. Not real exam dumps.\n")
    f.write("const QUESTIONS = ")
    json.dump(questions, f, ensure_ascii=False, indent=2)
    f.write(";\n")
print(len(questions))
